import { z } from "zod";

// ============================================================
// Domain types — Creator Profile
// ============================================================

export const PlatformEnum = z.enum([
  "tiktok",
  "youtube_shorts",
  "xiaohongshu",
  "douyin",
  "instagram_reels",
]);
export type Platform = z.infer<typeof PlatformEnum>;

export const VideoDurationEnum = z.enum([
  "<30s",
  "30-60s",
  "1-3min",
  "3min+",
]);
export type VideoDuration = z.infer<typeof VideoDurationEnum>;

export const ContentStyleEnum = z.enum([
  "professional",
  "casual_humor",
  "storytelling",
  "tutorial",
]);
export type ContentStyle = z.infer<typeof ContentStyleEnum>;

export interface CreatorProfile {
  id: string; // UUID generated by Supabase
  device_id: string;
  platform: Platform;
  category: string;
  target_audience: string;
  content_style: ContentStyle;
  video_duration: VideoDuration;
  language: string;
  created_at: string;
  updated_at: string;
}

// ============================================================
// Topic Generation
// ============================================================

export interface TopicIdea {
  title: string;
  angle: string;
  description: string;
}

export const TopicIdeaSchema: z.ZodType<TopicIdea> = z.object({
  title: z.string(),
  angle: z.string(),
  description: z.string(),
});

export const TopicGenerationResultSchema = z.object({
  ideas: z.array(TopicIdeaSchema).min(1).max(5),
});
export type TopicGenerationResult = z.infer<
  typeof TopicGenerationResultSchema
>;

export interface TopicGenerationRequest {
  topic: string;
  profile_id?: string;
}

// ============================================================
// Content Plan
// ============================================================

export const ContentPlanResultSchema = z.object({
  opening_hook: z.string(),
  content_structure: z.string(),
  key_points: z.array(z.string()).min(1),
  ending_cta: z.string(),
  cover_text: z.string(),
});
export type ContentPlanResult = z.infer<typeof ContentPlanResultSchema>;

export interface ContentPlanRequest {
  selected_topic: TopicIdea;
  profile_id?: string;
}

// ============================================================
// Video Analysis
// ============================================================

export const VideoMetricsSchema = z.object({
  views: z.number().int().nonnegative(),
  likes: z.number().int().nonnegative(),
  comments: z.number().int().nonnegative(),
  saves: z.number().int().nonnegative(),
  shares: z.number().int().nonnegative(),
});
export type VideoMetrics = z.infer<typeof VideoMetricsSchema>;

export const EngagementLevelEnum = z.enum(["low", "medium", "high", "viral"]);
export type EngagementLevel = z.infer<typeof EngagementLevelEnum>;

export const AnalysisResultSchema = z.object({
  engagement_rate: z.number(),
  engagement_level: EngagementLevelEnum,
  suggestions: z.array(z.string()).min(1),
});
export type AnalysisResult = z.infer<typeof AnalysisResultSchema>;

export interface AnalysisRequest {
  metrics: VideoMetrics;
  video_topic?: string;
  profile_id?: string;
}

// ============================================================
// Engagement metrics (pre-AI calculation)
// ============================================================

export interface EngagementMetrics {
  rate: number; // percentage
  level: EngagementLevel;
}

// ============================================================
// Shared UI state
// ============================================================

export type AsyncState<T> =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "success"; data: T }
  | { status: "error"; error: string };

// ============================================================
// App configuration
// ============================================================

export interface AppConfig {
  deepseekApiKey: string;
  deepseekModel: string;
  supabaseUrl: string;
  supabaseAnonKey: string;
}

// ============================================================
// User-facing error
// ============================================================

export interface UserFacingError {
  message: string;
  code: string;
}
